!  Physical Constants
      real*8, parameter :: pi = 3.141592653589793
      real*8, parameter :: c = 2.99792458d8                 ! Speed of light [m/s]
      real*8, parameter :: e = 1.60217646d-19               ! Elementary charge [C]
      real*8, parameter :: kb = 1.38065030d-23              ! Boltzman constant [J/K]
      real*8, parameter :: kbeV = kb/e                      ! Boltzman constant [eV/K]
      real*8, parameter :: h = 6.626d-34                    ! Planck constant
      real*8, parameter :: mH = 1.6735575e-27               ! Hydrogen atom mass [kg]
      real*8, parameter :: mp = 1.67262158d-27              ! Proton mass [kg]
      real*8, parameter :: me = 9.10938188d-31              ! Electron mass [kg]
      real*8, parameter :: Re = 6.371009d6                  ! Earth radius [m]
      real*8, parameter :: mEarth = 5.9722e24               ! Earth mass [kg]
      real*8, parameter :: constG = 6.6743e-11              ! Gravitational constant
      real*8, parameter :: GM = constG * mEarth             ! For convenience
      real*8, parameter :: arad = 0.1774d-2                 ! For radiation pressure [m/s^2]
      real*8, parameter :: Wrot = 1.9910d-7                 ! Earth's angular speed [rad/s]




